export const environment = {
  production: true,
  apiUrl: ' https://api.ihelpchat.com',
  authToken: 'Bearer Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJicnVub0BpaGVscGNoYXQuY29tIiwianRpIjoiMWFkMTVlNTAtZWY3Ni00MmE4LTllMTYtNDM2MjliMzNiMDA0IiwiaWF0IjoxNjI2MzY5MzI2LCJyb2wiOiJhcGlfYWNjZXNzIiwiaWQiOiI1ZjQzZjc4NTc1ZDkwYzFkMWRlZWM0NDYiLCJuYmYiOjE2MjYzNjkzMjYsImV4cCI6MTYzNjczNzMyNiwiaXNzIjoiY29temFkYS5jb20uYnIiLCJhdWQiOiJDb216YWRhQXVkaWVuY2llU2x6In0.jxJnneMvot8BnbTXHwSk3vj0aeST0lgKgAlCb-JD1H4'
};
